---
- name: add InfluxDB key repository
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present
  become: yes

- name: add InfluxDB repository
  apt_repository:
    repo: deb https://repos.influxdata.com/{{ ansible_facts.distribution|lower }} {{ ansible_facts.distribution_release }} stable
    state: present
    filename: influxdb
    update_cache: yes
  become: yes
